title: Chris's Awesome Blog
email: chris@nunciato.org
description: > # this means to ignore newlines until "baseurl:"
  Chris lives on a farm in Ohio and misses Seattle but totally likes it here, too.
baseurl: ''
url: http://jekyll-blog-test.s3-website-us-west-2.amazonaws.com
twitter_username: cnunciato
github_username:  cnunciato
permalink: pretty
markdown: rdiscount
exclude:
  - vendor
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - README.md
prose:
  rooturl: _posts
  siteurl: http://jekyll-blog-test.s3-website-us-west-2.amazonaws.com/
  media: images
  ignore:
    - .gitkeep
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: default
      - name: author
        field:
          element: text
          label: Author
          value: ''

