title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ''
url: http://jekyll-blog-test.s3-website-us-west-2.amazonaws.com
twitter_username: cnunciato
github_username:  cnunciato
permalink: pretty
markdown: rdiscount
exclude:
  - vendor
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - README.md
prose:
  rooturl: _posts
  siteurl: http://jekyll-blog-test.s3-website-us-west-2.amazonaws.com/
  media: images
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: default
      - name: title
        field:
          element: text
          label: Title
          value: ''
      - name: author
        field:
          element: text
          label: Author
          value: ''

